FirstProject - Test/Controllers/LoginController.cs
using FirstProjectRepository.Helpers;
using FirstProjectRepository.Repository;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.CookiePolicy;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace FirstProject___Test.Controllers
{
    public class LoginController : Controller
    {
        private readonly UserRepository _userRepository;
        private readonly string _secretKey;
        private readonly Crypt _crypt;
        public LoginController(UserRepository userRepository,Crypt crypt)
        {
            _userRepository = userRepository;
            _secretKey = "my - 32 - character - ultra - secure - and - ultra - long - secret";
            _crypt = crypt;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string username, string password)
        {
            var user = _userRepository.GetUserByUsername(username);
            if (user == null || !VerifyPassword(password, user.password))
            {
                ViewBag.ErrorMessage = "Invalid username or password";
                return View();
            }
            var token = GenerateJwtToken(user.userToken);

            Response.Cookies.Append("jwt", token, new CookieOptions
            {
                HttpOnly = true,
                Secure = true,
                SameSite = SameSiteMode.None,
                Expires = DateTime.UtcNow.AddMinutes(30)
            });

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
       
        [HttpGet]
        public IActionResult Logout()
        {
           
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> LogoutConfirmed()
        {
            
            
                
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

              

                
                return RedirectToAction("Index", "Home");
            
        }
        private string GenerateJwtToken(Guid userToken)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var key = Encoding.UTF8.GetBytes(_secretKey);
            var tokenDecriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity(new Claim[] {
                    new Claim(ClaimTypes.NameIdentifier, userToken.ToString())
                }),
                Audience = "https://localhost",
                Issuer = "https://localhost",
                Expires = DateTime.UtcNow.AddMinutes(30),
                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key),
                SecurityAlgorithms.HmacSha256Signature)
            };
            var token = tokenHandler.CreateToken(tokenDecriptor);
            return tokenHandler.WriteToken(token);
        }
        private bool VerifyPassword(string inputPassword, string storedHash)
        {
            string inputHash = _crypt.ComputeHash(inputPassword);
            return storedHash == inputHash;
        }
        

    }
}

FirstProject - Test/Controllers/PostController.cs
using FirstProject___Test.Models;
using FirstProjectRepository.Repository;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using FirstProjectRepository.DBModels;
using System.Drawing;
using System.Security.Claims;
using FirstProjectRepository.UsefullModels;
using FirstProjectRepository.Helpers;
using FirstProject___Test.Helpful;

namespace FirstProject___Test.Controllers
{
    public class PostController : Controller
    {
        private readonly PostRepository _postRepository;
        private readonly UserRepository _userRepository;
        private readonly CommentRepository _commentRepository;
        private readonly VoteRepository _voteRepository;
        
        public PostController(PostRepository postRepository,UserRepository userRepository, CommentRepository commentRepository, 
            VoteRepository voteRepository)
        {
            _postRepository = postRepository;
            _userRepository = userRepository;
            _commentRepository = commentRepository;
            _voteRepository = voteRepository;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            List<Post> posts = _postRepository.GetAllPosts();
            return View(posts);
        }
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        public IActionResult Add() { return View(); }
        [HttpPost]

        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        public IActionResult Add(Post post)
        {


            if (ModelState.IsValid)
            {
                post.userToken = UserTokenHelper.GetCurrentUserToken(HttpContext);
                post.createdAt = DateTime.UtcNow;

                
                _postRepository.InsertPost(post);
                return RedirectToAction("Index", "Home");
            }

            return View(post);
        }
        [HttpGet]
        [Authorize]
        public IActionResult Edit(int id)
        {
            
            var post = _postRepository.GetPostById(id);

            
            if (post == null || post.userToken != UserTokenHelper.GetCurrentUserToken(HttpContext))
            {
                return NotFound(); 
            }

            return View(post);
        }

        
        [HttpPost]
        [Authorize]
        public IActionResult Edit(int id, Post post)
        {
            
            var existingPost = _postRepository.GetPostById(id);

            
            if (existingPost == null || existingPost.userToken != UserTokenHelper.GetCurrentUserToken(HttpContext))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
               
                existingPost.title = post.title;
                existingPost.text = post.text;
                existingPost.url = post.url;
                
                _postRepository.UpdatePost(existingPost);

                
                return RedirectToAction("Index", "Home");
            }

            
            return View(post);
        }
        public IActionResult Newest()
        {
            List<PostWithUsername> posts = _postRepository.GetAllPostsSortedByDate();
            return View(posts);
        }
        [Authorize]
        public IActionResult Delete(int id)
        {
            var post = _postRepository.GetPostById(id);

            if (post == null || post.userToken != UserTokenHelper.GetCurrentUserToken(HttpContext))
            {
                return NotFound();
            }

            return View(post);
        }
        [HttpPost, ActionName("Delete")]
        [Authorize]
        public IActionResult ConfirmDelete(int id)
        {
            var post = _postRepository.GetPostById(id);

            if (post == null || post.userToken != UserTokenHelper.GetCurrentUserToken(HttpContext))
            {
                return NotFound();
            }
            _commentRepository.DeleteCommentsByPostId(id);
            _voteRepository.RemoveVotesByPostId(id);

            _postRepository.DeletePost(id);

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public IActionResult MyPosts()
        {
            var userToken = UserTokenHelper.GetCurrentUserToken(HttpContext);
            var posts = _postRepository.GetPostByUserId(userToken);
            return View(posts);
        }
        [AllowAnonymous]
        public IActionResult ViewPost(int id)
        {
            ViewBag.CurrentUserToken = UserTokenHelper.GetCurrentUserToken(HttpContext);
           
            var postWithComments = _postRepository.GetPostAndComments(id);
            return View(postWithComments);
        }
        [HttpPost]
        public IActionResult Upvote(int postId)
        {
            var post = _postRepository.GetPostById(postId);
            if (post == null)
            {
                return NotFound();
            }

            var userToken = UserTokenHelper.GetCurrentUserToken(HttpContext);
            if (_voteRepository.hasUserVoted(userToken, postId))
            {
                if (_voteRepository.GetUserVoteType(userToken, postId) == (int)VoteType.Upvote)
                {

                    post.upvotes--;
                    _postRepository.UpdateUpvotes(postId, post.upvotes);
                    _voteRepository.RemoveVote(userToken, postId);
                }
                else
                {
                    post.downvotes--;
                    _postRepository.UpdateDownvotes(postId, post.downvotes);
                    _voteRepository.RemoveVote(userToken, postId);
                }
            }
            else
            {
                
                post.upvotes++;
                _postRepository.UpdateUpvotes(postId, post.upvotes);
                var vote = new Vote
                {
                    userToken = userToken,
                    postId = postId,
                    voteType = VoteType.Upvote
                };
                _voteRepository.AddVote(vote);
            }
            int votecount = post.upvotes - post.downvotes;
            return Json(new { votecount = votecount });
        }

        [HttpPost]
        public IActionResult Downvote(int postId)
        {
            var post = _postRepository.GetPostById(postId);
            if (post == null)
            {
                return NotFound();
            }

            var userToken = UserTokenHelper.GetCurrentUserToken(HttpContext);
            if (_voteRepository.hasUserVoted(userToken, postId))
            {
                if (_voteRepository.GetUserVoteType(userToken, postId) == (int)VoteType.Downvote)
                {
                    post.downvotes--;
                    _postRepository.UpdateDownvotes(postId, post.downvotes);
                    _voteRepository.RemoveVote(userToken, postId);
                }
                else
                {
                    post.upvotes--;
                    _postRepository.UpdateUpvotes(postId, post.upvotes);
                    _voteRepository.RemoveVote(userToken, postId);
                }
            }
            else
            {
            
                post.downvotes++;
                _postRepository.UpdateDownvotes(postId, post.downvotes);
                var vote = new Vote
                {
                    userToken = userToken,
                    postId = postId,
                    voteType = VoteType.Downvote
                };
                _voteRepository.AddVote(vote);
            }
            int votecount = post.upvotes - post.downvotes;

            return Json(new { votecount = votecount });
        }
    }

}

FirstProject - Test/Controllers/RegisterController.cs
using FirstProject___Test.Models;
using FirstProjectRepository.DBModels;
using FirstProjectRepository.Helpers;
using FirstProjectRepository.Repository;
using Microsoft.AspNetCore.Mvc;

namespace FirstProject___Test.Controllers
{
    public class RegisterController : Controller
    {
        private readonly UserRepository _userRepository;
        private readonly Crypt _crypt;
        public RegisterController(UserRepository userRepository,Crypt crypt)
        {
            _userRepository = userRepository;
            _crypt = crypt;
        }
        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SignUp(RegistrationModel model) 
        {
            if (ModelState.IsValid)
            {
                if (_userRepository.GetUserByUsername(model.Username) != null)
                {
                    ModelState.AddModelError("Username", "Username Already Taken");
                }
                if(_userRepository.GetUserByEmail(model.Email) != null)
                {
                    ModelState.AddModelError("Email", "Email Already Taken");
                }
                else
                {
                    var newUser = new User
                    {
                        username = model.Username,
                        email = model.Email,
                        password = _crypt.ComputeHash(model.Password)
                    };
                    _userRepository.InsertUser(newUser);
                    return RedirectToAction("Login","Login");
                   
                }
            }
            return View(model);
        }

        
    }
}

FirstProject - Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstProject___Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstProject___Test.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Drive News</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Post" asp-action="Newest">Newest Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Post" asp-action="Index">Posts</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Post" asp-action="Add">Add Post</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Post" asp-action="MyPosts">My Posts</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Register" asp-action="SignUp">Register</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Drive News- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Rules</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>